### ISSUE TITLE
MacOS compatibility issue

### ISSUE THREAD

**Issue by n4l5u0r** [castframework/keyset-maker#2]
https://github.com/castframework/keyset-maker/blob/ce0886edf5629976a73a47d1e044a962f9870b58/src/cli.js#L1

```bash
../.bin/keyset-maker: /bin/env: bad interpreter: No such file or directory
``` 
when env is located in `/usr/bin/env` like on MacOS 12.2

have to overwrite the package line with `#!/usr/bin/env node` for the command `make start` to work properly.

**Comment by wid** [comment]
Hi man it's fixed !
